title: Article
preset: page
pages: false

fields:
  cover: 
    label: Image de couverture
    type: files
    mode: single
    width: 1/2
  coveryellow: 
    label: Filtre jaune de couverture
    type: files
    mode: single
    width: 1/2
    help: Choisir une image png avec les motifs jaune
  covercolor:
    label: Couleur de fond
    type: radio 
    options: 
      black: Noir
      gray: Gris
      lightgray: Gris clair 
    help: Choisir soit une photo de couverture soit une couleur de fond
  imgleft: 
    label: Image colonne de gauche
    type: files
    mode: single
    width: 1/2
  infos: 
    label: Texte synthétique
    type: markdown
    size: small
    help: S'affiche dans la colonne de gauche
  text:
    label: Texte
    type: markdown
    size: medium
    help: S'affiche dans la colonne de droite
  imageslist: 
    label: Images
    type: files

