title: Site
# preset: pages
# unlisted: true

tabs:
  pages:
    label: Pages
    icon: page
    columns:
      - width: 1/2
        sections:
          pages:
            type: pages
            headline: Pages
  settings:
    label: Paramètres
    icon: settings
    columns:
      - width: 1/3
        sections:
          images:
            type: files
            template: image
            info: "{{ file.dimensions }}"
            size: small
      - width: 1/2
        fields:
          submenu: 
            label: Pages à afficher dans le petit menu
            type: pages
            query: site.children
          logo: 
            label: Logo du site
            type: files
            multiple: false
          address: 
            label: Adresse
            type: markdown
            size: small
          social: 
            label: Réseaux sociaux
            type: structure
            fields: 
              link: 
                label: Lien
                type: url
              text: 
                label: Texte
                type: text
              icon: 
                label: Icône
                type: text
                help: Pour trouver le code corresondant à l'icône aller sur https://fontawesome.com/icons/
          author: 
            label: Auteur
            type: text
          keywords:
            label: Mots-clés (pour les moteurs de recherche)
            type: tags
          description: 
            label: Description (pour les moteurs de recherche)
            type: textarea
            size: small
          copyright: 
            label: Copyright
            type: text


